	
	
export TRACKING_DATABASE_DEBUG=true
export TRACKING_DATABASE_PASSWORD=Manager1
export TRACKING_DATABASE_PORT=1433
export TRACKING_DATABASE_ADDRESS=192.168.56.103
export TRACKING_DATABASE_USER=tracking
export TRACKING_DATABASE_NAME=tracking
export TRACKING_HTTP_PORT=8080

	